"""empty message

Revision ID: 3d8f2a0c2193
Revises: f7a6e5e6acfa
Create Date: 2021-12-14 23:18:59.940572

"""

# revision identifiers, used by Alembic.
revision = '3d8f2a0c2193'
down_revision = 'f7a6e5e6acfa'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
