"""empty message

Revision ID: 68e102682549
Revises: b17311fd2332
Create Date: 2021-12-14 12:51:33.789633

"""

# revision identifiers, used by Alembic.
revision = '68e102682549'
down_revision = 'b17311fd2332'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
