"""empty message

Revision ID: 752ff870a72c
Revises: 836c17d88fa8
Create Date: 2021-12-13 23:38:41.513054

"""

# revision identifiers, used by Alembic.
revision = '752ff870a72c'
down_revision = '836c17d88fa8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
