"""empty message

Revision ID: 7574a4a3ec41
Revises: 68e102682549
Create Date: 2021-12-14 14:02:08.551561

"""

# revision identifiers, used by Alembic.
revision = '7574a4a3ec41'
down_revision = '68e102682549'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
