"""empty message

Revision ID: 836c17d88fa8
Revises: e0d55eceba2a
Create Date: 2021-12-13 23:31:06.485147

"""

# revision identifiers, used by Alembic.
revision = '836c17d88fa8'
down_revision = 'e0d55eceba2a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
