"""empty message

Revision ID: b17311fd2332
Revises: ef46c6c9e59b
Create Date: 2021-12-14 11:13:37.193862

"""

# revision identifiers, used by Alembic.
revision = 'b17311fd2332'
down_revision = 'ef46c6c9e59b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
