"""empty message

Revision ID: bd89bfb027fc
Revises: 7574a4a3ec41
Create Date: 2021-12-14 20:19:27.622648

"""

# revision identifiers, used by Alembic.
revision = 'bd89bfb027fc'
down_revision = '7574a4a3ec41'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
