"""empty message

Revision ID: e0d55eceba2a
Revises: 4c9f007d4e9b
Create Date: 2021-12-13 22:39:56.016553

"""

# revision identifiers, used by Alembic.
revision = 'e0d55eceba2a'
down_revision = '4c9f007d4e9b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
