"""empty message

Revision ID: ef46c6c9e59b
Revises: 836c17d88fa8
Create Date: 2021-12-14 10:40:10.972522

"""

# revision identifiers, used by Alembic.
revision = 'ef46c6c9e59b'
down_revision = '836c17d88fa8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
