"""empty message

Revision ID: f7a6e5e6acfa
Revises: bd89bfb027fc
Create Date: 2021-12-14 22:14:37.117325

"""

# revision identifiers, used by Alembic.
revision = 'f7a6e5e6acfa'
down_revision = 'bd89bfb027fc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
